name: DebugBuild
on:
  push:
    branches:
      - GE3_01-05

env:
  SOLUTION_FILE_PATH: project/DirectXGame_CG2-CG2_Game.sin
  CONFIGURATION: Debug

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4 

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - name: Build
        run: |
          msbuild ${{env.SOLUTION_FILE_PATH}} /p:Platform=x64 /p:Configuration=${{env.CONFIGURATION}}
